spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false

#logging:
#  level:
#    root: debug

test:
  rightAnswersCountToPass: 3
  locale: en-US
  fileNameByLocaleTag:
    ru-RU: questions_ru_RU.csv
    en-US: questions_en_US.csv